export type UnitKind =
  | "count"
  | "length"
  | "area"
  | "volume"
  | "mass"
  | "time"
  | "energy"
  | "speed"
  | "data"
  | "frequency";

export type OutputKind = UnitKind | "multiple";

export type Source = {
  label: string;
  url: string;
};

export type ContextEntry = {
  id: string;
  name: string;
  shortName: string;
  input: UnitKind;
  output: OutputKind;
  group: string;
  factor: number;
  unitSingular?: string;
  unitPlural?: string;
  resultPhrase: string;
  basis: string;
  sources: Source[];
  goodRange?: [number, number];
  glyph: "stack" | "field" | "cosmic" | "grain" | "body" | "tower" | "water" | "food" | "spark" | "data";
  accent: string;
};

export const UNIT_KINDS: {
  id: UnitKind;
  label: string;
  baseLabel: string;
  placeholder: string;
}[] = [
  { id: "count", label: "Count", baseLabel: "things", placeholder: "1,000,000" },
  { id: "length", label: "Length", baseLabel: "metres", placeholder: "8848" },
  { id: "area", label: "Area", baseLabel: "square metres", placeholder: "7140" },
  { id: "volume", label: "Volume", baseLabel: "litres", placeholder: "2500000" },
  { id: "mass", label: "Mass", baseLabel: "kilograms", placeholder: "6000" },
  { id: "time", label: "Time", baseLabel: "seconds", placeholder: "86400" },
  { id: "energy", label: "Energy", baseLabel: "joules", placeholder: "1000000" },
  { id: "speed", label: "Speed", baseLabel: "metres/second", placeholder: "29" },
  { id: "data", label: "Data", baseLabel: "bytes", placeholder: "1000000000" },
  { id: "frequency", label: "Frequency", baseLabel: "hertz", placeholder: "50" },
];

export const CONTEXTS: ContextEntry[] = [
  {
    id: "ant-stack",
    name: "Stack of ants",
    shortName: "ants stacked",
    input: "count",
    output: "length",
    group: "Nature",
    factor: 0.003,
    resultPhrase: "high if every item were a 3 mm ant",
    basis: "Uses a small worker ant length of 3 mm. Real ants vary wildly by species, so this is a deliberately friendly middle-of-the-road estimate.",
    sources: [
      { label: "Wikipedia: Ant", url: "https://en.wikipedia.org/wiki/Ant" },
      { label: "Wikipedia: Solenopsis molesta size range", url: "https://en.wikipedia.org/wiki/Solenopsis_molesta" },
    ],
    goodRange: [0.01, 10000000],
    glyph: "stack",
    accent: "#d74e21",
  },
  {
    id: "sand-beach",
    name: "Beach made of sand grains",
    shortName: "beach length",
    input: "count",
    output: "length",
    group: "Nature",
    factor: 1 / 100000000000,
    resultPhrase: "of 20 m wide, 1 m deep beach",
    basis: "Assumes roughly 0.5 mm grains with about 60 percent packing, giving around 100 billion grains per metre of a 20 m wide, 1 m deep beach strip.",
    sources: [
      { label: "Wikipedia: Grain size", url: "https://en.wikipedia.org/wiki/Grain_size" },
      { label: "Wikipedia: Sand", url: "https://en.wikipedia.org/wiki/Sand" },
    ],
    goodRange: [0.001, 1000000],
    glyph: "grain",
    accent: "#c88a2d",
  },
  {
    id: "milky-way-stars",
    name: "Milky Way loads of stars",
    shortName: "Milky Ways of stars",
    input: "count",
    output: "count",
    group: "Cosmic",
    factor: 1 / 100000000000,
    unitSingular: "Milky Way of stars",
    unitPlural: "Milky Ways of stars",
    resultPhrase: "if your number is stars",
    basis: "Uses 100 billion stars as the lower end of the common Milky Way estimate.",
    sources: [
      { label: "Wikipedia: Milky Way", url: "https://en.wikipedia.org/wiki/Milky_Way" },
    ],
    goodRange: [0.01, 1000000000],
    glyph: "cosmic",
    accent: "#3563a6",
  },
  {
    id: "brain-synapses",
    name: "Human-brain synapses",
    shortName: "brains of synapses",
    input: "count",
    output: "count",
    group: "Body",
    factor: 1 / 100000000000000,
    unitSingular: "adult brain of synapses",
    unitPlural: "adult brains of synapses",
    resultPhrase: "if your number is synapses",
    basis: "Uses the familiar order-of-magnitude estimate of 100 trillion synapses in the adult human brain.",
    sources: [
      { label: "Wikipedia: Brain", url: "https://en.wikipedia.org/wiki/Brain" },
      { label: "Wikipedia: Chemical synapse", url: "https://en.wikipedia.org/wiki/Chemical_synapse" },
    ],
    goodRange: [0.01, 1000000],
    glyph: "body",
    accent: "#b5385b",
  },
  {
    id: "human-genomes",
    name: "Human genomes",
    shortName: "human genomes",
    input: "count",
    output: "count",
    group: "Body",
    factor: 1 / 3000000000,
    unitSingular: "human genome",
    unitPlural: "human genomes",
    resultPhrase: "if your number is DNA bases",
    basis: "NHGRI gives about 3 billion bases and about 20,000 genes for the human genome.",
    sources: [
      { label: "NHGRI DNA fact sheet", url: "https://www.genome.gov/about-genomics/fact-sheets/Deoxyribonucleic-Acid-Fact-Sheet" },
    ],
    goodRange: [0.01, 1000000000],
    glyph: "body",
    accent: "#8e4a93",
  },
  {
    id: "shakespeare-words",
    name: "Complete Shakespeare word counts",
    shortName: "Shakespeares",
    input: "count",
    output: "count",
    group: "Culture",
    factor: 1 / 884647,
    unitSingular: "complete Shakespeare",
    unitPlural: "complete Shakespeares",
    resultPhrase: "if your number is words",
    basis: "Uses the commonly cited 884,647-word total for Shakespeare's complete works.",
    sources: [
      { label: "Open Source Shakespeare statistics", url: "https://www.opensourceshakespeare.org/stats/" },
    ],
    goodRange: [0.01, 1000000],
    glyph: "data",
    accent: "#6d5f2f",
  },
  {
    id: "a4-pages",
    name: "A4 typed pages",
    shortName: "A4 pages",
    input: "count",
    output: "count",
    group: "Everyday",
    factor: 1 / 500,
    unitSingular: "single-spaced A4 page",
    unitPlural: "single-spaced A4 pages",
    resultPhrase: "if your number is words",
    basis: "A round working estimate of 500 words per single-spaced A4 page.",
    sources: [
      { label: "Wikipedia: Words per page", url: "https://en.wikipedia.org/wiki/Words_per_page" },
    ],
    goodRange: [0.1, 1000000000],
    glyph: "data",
    accent: "#476f63",
  },
  {
    id: "brick-wall-area",
    name: "Wall made of bricks",
    shortName: "brick wall",
    input: "count",
    output: "area",
    group: "Everyday",
    factor: 0.0165,
    resultPhrase: "of wall face from standard UK bricks",
    basis: "Uses a UK-style 215 x 65 mm brick face plus mortar allowance, rounded to 0.0165 m2 per visible brick.",
    sources: [
      { label: "Wikipedia: Brick dimensions", url: "https://en.wikipedia.org/wiki/Brick#Dimensions" },
    ],
    goodRange: [0.1, 1000000],
    glyph: "field",
    accent: "#9d4d2f",
  },
  {
    id: "resting-heartbeats",
    name: "Resting heartbeats",
    shortName: "heartbeats",
    input: "time",
    output: "count",
    group: "Body",
    factor: 1,
    unitSingular: "resting heartbeat",
    unitPlural: "resting heartbeats",
    resultPhrase: "at 60 beats per minute",
    basis: "Uses 60 beats per minute as a deliberately simple resting-heart-rate reference.",
    sources: [
      { label: "American Heart Association: target heart rates", url: "https://www.heart.org/en/healthy-living/fitness/fitness-basics/target-heart-rates" },
    ],
    goodRange: [1, 10000000000],
    glyph: "body",
    accent: "#c73535",
  },
  {
    id: "everest-height",
    name: "Mount Everest",
    shortName: "Everests",
    input: "length",
    output: "multiple",
    group: "Cosmic",
    factor: 1 / 8848.86,
    unitSingular: "Mount Everest",
    unitPlural: "Mount Everests",
    resultPhrase: "above sea level",
    basis: "Uses the 2020 China-Nepal declared height of 8,848.86 m.",
    sources: [
      { label: "Britannica: Mount Everest", url: "https://www.britannica.com/place/Mount-Everest" },
    ],
    goodRange: [0.01, 1000000],
    glyph: "tower",
    accent: "#4a7c85",
  },
  {
    id: "eiffel-tower",
    name: "Eiffel Tower",
    shortName: "Eiffel Towers",
    input: "length",
    output: "multiple",
    group: "Buildings",
    factor: 1 / 330,
    unitSingular: "Eiffel Tower",
    unitPlural: "Eiffel Towers",
    resultPhrase: "including antennas",
    basis: "The official Eiffel Tower site lists a current height of 1,083 feet, about 330 m.",
    sources: [
      { label: "Eiffel Tower official figures", url: "https://www.toureiffel.paris/en/the-monument/key-figures" },
    ],
    goodRange: [0.01, 1000000],
    glyph: "tower",
    accent: "#a84d7a",
  },
  {
    id: "empire-state",
    name: "Empire State Building",
    shortName: "Empire States",
    input: "length",
    output: "multiple",
    group: "Buildings",
    factor: 1 / 443,
    unitSingular: "Empire State Building",
    unitPlural: "Empire State Buildings",
    resultPhrase: "including spire and antenna",
    basis: "The official ESB site gives 1,454 feet, or about 443 m, including spire and antenna.",
    sources: [
      { label: "Empire State Building facts", url: "https://www.esbnyc.com/about/facts-figures" },
    ],
    goodRange: [0.01, 1000000],
    glyph: "tower",
    accent: "#5d6470",
  },
  {
    id: "earth-moon",
    name: "Earth to Moon",
    shortName: "moon trips",
    input: "length",
    output: "multiple",
    group: "Cosmic",
    factor: 1 / 384400000,
    unitSingular: "Earth-Moon distance",
    unitPlural: "Earth-Moon distances",
    resultPhrase: "using the average distance",
    basis: "NASA gives the Moon's average distance from Earth as 384,400 km.",
    sources: [
      { label: "NASA Moon facts", url: "https://science.nasa.gov/moon/facts/" },
    ],
    goodRange: [0.001, 1000000],
    glyph: "cosmic",
    accent: "#536db2",
  },
  {
    id: "earth-sun",
    name: "Earth to Sun",
    shortName: "astronomical units",
    input: "length",
    output: "multiple",
    group: "Cosmic",
    factor: 1 / 149597870700,
    unitSingular: "astronomical unit",
    unitPlural: "astronomical units",
    resultPhrase: "at the IAU-defined AU",
    basis: "The astronomical unit is defined as exactly 149,597,870,700 m.",
    sources: [
      { label: "Wikipedia: Astronomical unit", url: "https://en.wikipedia.org/wiki/Astronomical_unit" },
      { label: "IAU 2012 resolution", url: "https://www.iau.org/static/resolutions/IAU2012_English.pdf" },
    ],
    goodRange: [0.0001, 1000000],
    glyph: "cosmic",
    accent: "#df9d2f",
  },
  {
    id: "dna-cells",
    name: "Human-cell DNA",
    shortName: "cells of DNA",
    input: "length",
    output: "count",
    group: "Body",
    factor: 1 / 2,
    unitSingular: "cell's worth of DNA",
    unitPlural: "cells' worth of DNA",
    resultPhrase: "if stretched end to end",
    basis: "Uses the popular 2 m per human cell estimate, derived from about 3 billion DNA base pairs.",
    sources: [
      { label: "NHGRI DNA fact sheet", url: "https://www.genome.gov/about-genomics/fact-sheets/Deoxyribonucleic-Acid-Fact-Sheet" },
    ],
    goodRange: [0.01, 1000000000000],
    glyph: "body",
    accent: "#7f4aa5",
  },
  {
    id: "paper-stack-length",
    name: "Office paper stack",
    shortName: "sheets stacked",
    input: "length",
    output: "count",
    group: "Everyday",
    factor: 1 / 0.0001,
    unitSingular: "sheet of paper",
    unitPlural: "sheets of paper",
    resultPhrase: "at 0.1 mm per sheet",
    basis: "Uses 0.1 mm as a typical office-paper thickness.",
    sources: [
      { label: "Wikipedia: Paper density", url: "https://en.wikipedia.org/wiki/Paper_density" },
    ],
    goodRange: [1, 10000000000],
    glyph: "stack",
    accent: "#50735d",
  },
  {
    id: "human-hairs",
    name: "Human hairs",
    shortName: "hairs across",
    input: "length",
    output: "count",
    group: "Body",
    factor: 1 / 0.00007,
    unitSingular: "human hair width",
    unitPlural: "human hair widths",
    resultPhrase: "at 70 micrometres each",
    basis: "Human hair diameters vary a lot; 70 micrometres is a handy central estimate.",
    sources: [
      { label: "Wikipedia: Hair's breadth", url: "https://en.wikipedia.org/wiki/Hair%27s_breadth" },
    ],
    goodRange: [1, 10000000000],
    glyph: "body",
    accent: "#3d766f",
  },
  {
    id: "football-pitch-length",
    name: "Football pitch lengths",
    shortName: "pitch lengths",
    input: "length",
    output: "multiple",
    group: "Sport",
    factor: 1 / 105,
    unitSingular: "105 m football pitch length",
    unitPlural: "105 m football pitch lengths",
    resultPhrase: "touchline to touchline",
    basis: "Uses the 105 m top-level pitch length often used for international football.",
    sources: [
      { label: "IFAB: The field of play", url: "https://www.theifab.com/laws/latest/the-field-of-play/" },
      { label: "Wikipedia: Football pitch", url: "https://en.wikipedia.org/wiki/Football_pitch" },
    ],
    goodRange: [0.01, 1000000],
    glyph: "field",
    accent: "#3f8b45",
  },
  {
    id: "football-pitch-area",
    name: "Football pitches",
    shortName: "football pitches",
    input: "area",
    output: "multiple",
    group: "Sport",
    factor: 1 / 7140,
    unitSingular: "105 x 68 m football pitch",
    unitPlural: "105 x 68 m football pitches",
    resultPhrase: "using 7,140 m2",
    basis: "Uses a 105 x 68 m top-level association football pitch.",
    sources: [
      { label: "IFAB: The field of play", url: "https://www.theifab.com/laws/latest/the-field-of-play/" },
      { label: "Wikipedia: Football pitch", url: "https://en.wikipedia.org/wiki/Football_pitch" },
    ],
    goodRange: [0.01, 10000000],
    glyph: "field",
    accent: "#3f8b45",
  },
  {
    id: "us-football-area",
    name: "US football fields",
    shortName: "US football fields",
    input: "area",
    output: "multiple",
    group: "Sport",
    factor: 1 / 5351.215,
    unitSingular: "American football field",
    unitPlural: "American football fields",
    resultPhrase: "including end zones",
    basis: "Uses 360 ft by 160 ft, converted to 5,351 m2.",
    sources: [
      { label: "Wikipedia: American football field", url: "https://en.wikipedia.org/wiki/American_football_field" },
    ],
    goodRange: [0.01, 10000000],
    glyph: "field",
    accent: "#6d7d3f",
  },
  {
    id: "tennis-courts",
    name: "Tennis courts",
    shortName: "tennis courts",
    input: "area",
    output: "multiple",
    group: "Sport",
    factor: 1 / 260.87,
    unitSingular: "doubles tennis court",
    unitPlural: "doubles tennis courts",
    resultPhrase: "using the playing rectangle",
    basis: "A doubles court is 23.77 m by 10.97 m.",
    sources: [
      { label: "ITF tennis court dimensions", url: "https://www.itftennis.com/en/about-us/governance/rules-and-regulations/" },
      { label: "Wikipedia: Tennis court", url: "https://en.wikipedia.org/wiki/Tennis_court" },
    ],
    goodRange: [0.01, 10000000],
    glyph: "field",
    accent: "#5f8d35",
  },
  {
    id: "postage-stamps",
    name: "Postage stamps",
    shortName: "stamps",
    input: "area",
    output: "count",
    group: "Everyday",
    factor: 1 / 0.000525,
    unitSingular: "postage stamp",
    unitPlural: "postage stamps",
    resultPhrase: "at 25 x 21 mm each",
    basis: "Uses 25 x 21 mm as a small definitive stamp-sized rectangle.",
    sources: [
      { label: "Wikipedia: Postage stamp", url: "https://en.wikipedia.org/wiki/Postage_stamp" },
    ],
    goodRange: [1, 100000000000],
    glyph: "field",
    accent: "#c2463f",
  },
  {
    id: "manhattan",
    name: "Manhattan",
    shortName: "Manhattans",
    input: "area",
    output: "multiple",
    group: "Places",
    factor: 1 / 59100000,
    unitSingular: "Manhattan",
    unitPlural: "Manhattans",
    resultPhrase: "of land area",
    basis: "Uses about 59.1 km2 of land area for Manhattan.",
    sources: [
      { label: "Wikipedia: Manhattan", url: "https://en.wikipedia.org/wiki/Manhattan" },
    ],
    goodRange: [0.001, 1000000],
    glyph: "field",
    accent: "#397d87",
  },
  {
    id: "bathtubs",
    name: "Bathtubs",
    shortName: "bathtubs",
    input: "volume",
    output: "multiple",
    group: "Everyday",
    factor: 1 / 150,
    unitSingular: "bath",
    unitPlural: "baths",
    resultPhrase: "at 150 litres each",
    basis: "Uses 150 L as a rounded domestic bath volume.",
    sources: [
      { label: "Wikipedia: Bathtub", url: "https://en.wikipedia.org/wiki/Bathtub" },
    ],
    goodRange: [0.01, 10000000],
    glyph: "water",
    accent: "#2f7aa4",
  },
  {
    id: "coke-cans",
    name: "Drink cans",
    shortName: "330 ml cans",
    input: "volume",
    output: "count",
    group: "Food",
    factor: 1 / 0.33,
    unitSingular: "330 ml can",
    unitPlural: "330 ml cans",
    resultPhrase: "of fizzy drink",
    basis: "Uses the common UK and European 330 ml drink can.",
    sources: [
      { label: "Wikipedia: Drink can", url: "https://en.wikipedia.org/wiki/Drink_can" },
    ],
    goodRange: [1, 10000000000],
    glyph: "food",
    accent: "#bf3d39",
  },
  {
    id: "olympic-pools",
    name: "Olympic pools",
    shortName: "Olympic pools",
    input: "volume",
    output: "multiple",
    group: "Sport",
    factor: 1 / 2500000,
    unitSingular: "Olympic swimming pool",
    unitPlural: "Olympic swimming pools",
    resultPhrase: "at 2.5 million litres",
    basis: "Uses 50 m x 25 m x 2 m, a common nominal Olympic-pool volume.",
    sources: [
      { label: "World Aquatics competition regulations", url: "https://www.worldaquatics.com/rules/competition-regulations" },
      { label: "Wikipedia: Olympic-size swimming pool", url: "https://en.wikipedia.org/wiki/Olympic-size_swimming_pool" },
    ],
    goodRange: [0.001, 1000000],
    glyph: "water",
    accent: "#276fbd",
  },
  {
    id: "teaspoons",
    name: "Teaspoons",
    shortName: "teaspoons",
    input: "volume",
    output: "count",
    group: "Food",
    factor: 1 / 0.005,
    unitSingular: "teaspoon",
    unitPlural: "teaspoons",
    resultPhrase: "at 5 ml each",
    basis: "Uses the metric teaspoon definition of 5 ml.",
    sources: [
      { label: "Wikipedia: Spoon measurement", url: "https://en.wikipedia.org/wiki/Spoon_(unit)" },
    ],
    goodRange: [1, 100000000000],
    glyph: "food",
    accent: "#d1962d",
  },
  {
    id: "shipping-containers",
    name: "Shipping containers",
    shortName: "20 ft containers",
    input: "volume",
    output: "multiple",
    group: "Everyday",
    factor: 1 / 33200,
    unitSingular: "20 ft shipping container",
    unitPlural: "20 ft shipping containers",
    resultPhrase: "of internal volume",
    basis: "Uses about 33.2 m3, or 33,200 L, for a standard 20 ft container.",
    sources: [
      { label: "Wikipedia: Intermodal container", url: "https://en.wikipedia.org/wiki/Intermodal_container" },
    ],
    goodRange: [0.01, 10000000],
    glyph: "field",
    accent: "#8b7342",
  },
  {
    id: "elephants",
    name: "African elephants",
    shortName: "elephants",
    input: "mass",
    output: "multiple",
    group: "Nature",
    factor: 1 / 6000,
    unitSingular: "adult African elephant",
    unitPlural: "adult African elephants",
    resultPhrase: "at 6,000 kg each",
    basis: "Uses 6,000 kg as a rounded adult African elephant mass.",
    sources: [
      { label: "Wikipedia: African bush elephant", url: "https://en.wikipedia.org/wiki/African_bush_elephant" },
    ],
    goodRange: [0.001, 1000000],
    glyph: "body",
    accent: "#66714b",
  },
  {
    id: "ant-mass",
    name: "Ants by mass",
    shortName: "ants",
    input: "mass",
    output: "count",
    group: "Nature",
    factor: 1 / 0.000003,
    unitSingular: "3 mg ant",
    unitPlural: "3 mg ants",
    resultPhrase: "by body mass",
    basis: "Uses 3 mg as a simple small-ant mass estimate.",
    sources: [
      { label: "Wikipedia: Ant", url: "https://en.wikipedia.org/wiki/Ant" },
    ],
    goodRange: [1, 100000000000000],
    glyph: "grain",
    accent: "#aa5d2c",
  },
  {
    id: "house-bricks",
    name: "House bricks",
    shortName: "bricks",
    input: "mass",
    output: "count",
    group: "Everyday",
    factor: 1 / 2.2,
    unitSingular: "house brick",
    unitPlural: "house bricks",
    resultPhrase: "at 2.2 kg each",
    basis: "Uses 2.2 kg as a common fired-clay house brick mass.",
    sources: [
      { label: "Wikipedia: Brick", url: "https://en.wikipedia.org/wiki/Brick" },
    ],
    goodRange: [0.1, 1000000000],
    glyph: "field",
    accent: "#a14d30",
  },
  {
    id: "sugar-bags",
    name: "Bags of sugar",
    shortName: "sugar bags",
    input: "mass",
    output: "count",
    group: "Food",
    factor: 1,
    unitSingular: "1 kg bag of sugar",
    unitPlural: "1 kg bags of sugar",
    resultPhrase: "at supermarket size",
    basis: "Uses the familiar 1 kg sugar bag as a kitchen reference.",
    sources: [
      { label: "Wikipedia: Sugar", url: "https://en.wikipedia.org/wiki/Sugar" },
    ],
    goodRange: [0.1, 10000000000],
    glyph: "food",
    accent: "#b6812b",
  },
  {
    id: "paperclips",
    name: "Paper clips",
    shortName: "paper clips",
    input: "mass",
    output: "count",
    group: "Everyday",
    factor: 1 / 0.001,
    unitSingular: "paper clip",
    unitPlural: "paper clips",
    resultPhrase: "at about 1 g each",
    basis: "Uses 1 g as a simple estimate for a small paper clip.",
    sources: [
      { label: "Wikipedia: Paper clip", url: "https://en.wikipedia.org/wiki/Paper_clip" },
    ],
    goodRange: [1, 100000000000],
    glyph: "data",
    accent: "#566b77",
  },
  {
    id: "blinks",
    name: "Blinks",
    shortName: "blinks",
    input: "time",
    output: "count",
    group: "Body",
    factor: 10,
    unitSingular: "blink",
    unitPlural: "blinks",
    resultPhrase: "at 0.1 seconds each",
    basis: "Uses 0.1 seconds as a compact blink-duration estimate.",
    sources: [
      { label: "Wikipedia: Blink", url: "https://en.wikipedia.org/wiki/Blinking" },
    ],
    goodRange: [1, 100000000000],
    glyph: "body",
    accent: "#a74762",
  },
  {
    id: "human-lifetimes",
    name: "Human lifetimes",
    shortName: "80-year lives",
    input: "time",
    output: "multiple",
    group: "Body",
    factor: 1 / (80 * 365.25 * 24 * 60 * 60),
    unitSingular: "80-year lifetime",
    unitPlural: "80-year lifetimes",
    resultPhrase: "using a round lifespan",
    basis: "Uses 80 years as a deliberately round human-lifetime reference.",
    sources: [
      { label: "Wikipedia: Life expectancy", url: "https://en.wikipedia.org/wiki/Life_expectancy" },
    ],
    goodRange: [0.001, 1000000],
    glyph: "body",
    accent: "#854d75",
  },
  {
    id: "star-wars-saga",
    name: "Skywalker saga marathons",
    shortName: "Star Wars marathons",
    input: "time",
    output: "multiple",
    group: "Culture",
    factor: 1 / (1182 * 60),
    unitSingular: "nine-film Skywalker saga",
    unitPlural: "nine-film Skywalker sagas",
    resultPhrase: "back to back",
    basis: "Uses 1,182 minutes for Episodes I-IX combined, rounded from listed theatrical runtimes.",
    sources: [
      { label: "Wikipedia: Star Wars film runtimes", url: "https://en.wikipedia.org/wiki/Star_Wars#Skywalker_saga" },
    ],
    goodRange: [0.01, 1000000],
    glyph: "spark",
    accent: "#c39c2d",
  },
  {
    id: "earth-history-day",
    name: "Earth history day",
    shortName: "Earth-day scale",
    input: "time",
    output: "time",
    group: "Cosmic",
    factor: 86400 / (4.54e9 * 365.25 * 24 * 60 * 60),
    resultPhrase: "on a 24-hour history of Earth",
    basis: "Compresses Earth's roughly 4.54 billion year age into one day.",
    sources: [
      { label: "Wikipedia: Age of Earth", url: "https://en.wikipedia.org/wiki/Age_of_Earth" },
    ],
    goodRange: [0.000001, 86400],
    glyph: "cosmic",
    accent: "#557a4d",
  },
  {
    id: "hummingbird-wingbeats-time",
    name: "Hummingbird wingbeats",
    shortName: "wingbeats",
    input: "time",
    output: "count",
    group: "Nature",
    factor: 50,
    unitSingular: "hummingbird wingbeat",
    unitPlural: "hummingbird wingbeats",
    resultPhrase: "at 50 beats per second",
    basis: "Uses 50 Hz as a round hummingbird wingbeat reference.",
    sources: [
      { label: "Wikipedia: Hummingbird", url: "https://en.wikipedia.org/wiki/Hummingbird" },
    ],
    goodRange: [1, 1000000000000],
    glyph: "spark",
    accent: "#2f8b83",
  },
  {
    id: "mars-bars-energy",
    name: "Mars bars",
    shortName: "Mars bars",
    input: "energy",
    output: "count",
    group: "Food",
    factor: 1 / 962000,
    unitSingular: "Mars bar",
    unitPlural: "Mars bars",
    resultPhrase: "of food energy",
    basis: "Uses 230 kcal, converted with 4,184 J per food kilocalorie.",
    sources: [
      { label: "Wikipedia: Mars bar", url: "https://en.wikipedia.org/wiki/Mars_bar" },
      { label: "Wikipedia: Calorie", url: "https://en.wikipedia.org/wiki/Calorie" },
    ],
    goodRange: [0.01, 1000000000],
    glyph: "food",
    accent: "#8d4535",
  },
  {
    id: "lightbulb-hours",
    name: "100 W lightbulb hours",
    shortName: "bulb-hours",
    input: "energy",
    output: "count",
    group: "Everyday",
    factor: 1 / 360000,
    unitSingular: "100 W lightbulb-hour",
    unitPlural: "100 W lightbulb-hours",
    resultPhrase: "of old-school bulb glow",
    basis: "One 100 W bulb running for one hour uses 100 Wh, or 360,000 J.",
    sources: [
      { label: "Wikipedia: Watt-hour", url: "https://en.wikipedia.org/wiki/Watt-hour" },
    ],
    goodRange: [0.01, 100000000000],
    glyph: "spark",
    accent: "#d0982f",
  },
  {
    id: "boiling-cups",
    name: "Cups of water boiled",
    shortName: "boiled cups",
    input: "energy",
    output: "count",
    group: "Food",
    factor: 1 / 75000,
    unitSingular: "cup of water heated to boiling",
    unitPlural: "cups of water heated to boiling",
    resultPhrase: "from room temperature",
    basis: "Assumes 250 ml of water heated by about 70 C, using water's 4.184 J/g/C heat capacity.",
    sources: [
      { label: "Wikipedia: Heat capacity", url: "https://en.wikipedia.org/wiki/Heat_capacity" },
      { label: "Wikipedia: Water", url: "https://en.wikipedia.org/wiki/Properties_of_water" },
    ],
    goodRange: [0.01, 100000000000],
    glyph: "water",
    accent: "#2f7ca0",
  },
  {
    id: "hiroshima",
    name: "Hiroshima bomb yields",
    shortName: "Hiroshimas",
    input: "energy",
    output: "multiple",
    group: "Explosive",
    factor: 1 / (15 * 4.184e12),
    unitSingular: "Hiroshima bomb yield",
    unitPlural: "Hiroshima bomb yields",
    resultPhrase: "at 15 kilotons TNT",
    basis: "Uses 15 kilotons TNT, with one kiloton TNT defined as 4.184 terajoules.",
    sources: [
      { label: "Wikipedia: TNT equivalent", url: "https://en.wikipedia.org/wiki/TNT_equivalent" },
    ],
    goodRange: [0.000001, 1000000],
    glyph: "spark",
    accent: "#c1462f",
  },
  {
    id: "cheetahs",
    name: "Cheetahs",
    shortName: "cheetahs",
    input: "speed",
    output: "multiple",
    group: "Nature",
    factor: 1 / 29,
    unitSingular: "as fast as a cheetah",
    unitPlural: "as fast as a cheetah",
    resultPhrase: "using 104 km/h",
    basis: "Uses 29 m/s, about 104 km/h, as a reliably reported cheetah sprint speed.",
    sources: [
      { label: "Wikipedia: Cheetah speed", url: "https://en.wikipedia.org/wiki/Cheetah#Speed_and_acceleration" },
      { label: "National Geographic: Cheetah", url: "https://www.nationalgeographic.com/animals/mammals/facts/cheetah" },
    ],
    goodRange: [0.01, 1000000],
    glyph: "body",
    accent: "#c47e2e",
  },
  {
    id: "speed-of-light",
    name: "Speed of light",
    shortName: "speed of light",
    input: "speed",
    output: "multiple",
    group: "Cosmic",
    factor: 1 / 299792458,
    unitSingular: "the speed of light",
    unitPlural: "the speed of light",
    resultPhrase: "in vacuum",
    basis: "Uses the exact SI value 299,792,458 m/s.",
    sources: [
      { label: "NIST constants", url: "https://physics.nist.gov/cgi-bin/cuu/Value?c" },
      { label: "Wikipedia: Speed of light", url: "https://en.wikipedia.org/wiki/Speed_of_light" },
    ],
    goodRange: [0.001, 1000],
    glyph: "cosmic",
    accent: "#4259ad",
  },
  {
    id: "tgv",
    name: "High-speed trains",
    shortName: "TGVs",
    input: "speed",
    output: "multiple",
    group: "Everyday",
    factor: 1 / (320 / 3.6),
    unitSingular: "as fast as a high-speed train",
    unitPlural: "as fast as a high-speed train",
    resultPhrase: "at roughly 320 km/h",
    basis: "Uses 320 km/h as a typical high-speed rail operating speed.",
    sources: [
      { label: "Wikipedia: High-speed rail", url: "https://en.wikipedia.org/wiki/High-speed_rail" },
    ],
    goodRange: [0.01, 1000000],
    glyph: "spark",
    accent: "#b34242",
  },
  {
    id: "snails",
    name: "Crawling snails",
    shortName: "snails",
    input: "speed",
    output: "multiple",
    group: "Nature",
    factor: 1 / 0.001,
    unitSingular: "as fast as a snail",
    unitPlural: "as fast as a snail",
    resultPhrase: "at a typical crawling pace",
    basis: "Uses 1 mm/s as a memorable snail-speed estimate.",
    sources: [
      { label: "Wikipedia: Land snail", url: "https://en.wikipedia.org/wiki/Land_snail" },
    ],
    goodRange: [0.01, 1000000000],
    glyph: "grain",
    accent: "#6b7e39",
  },
  {
    id: "paper-stack-data",
    name: "Hard-drive paper stack",
    shortName: "paper-stack data",
    input: "data",
    output: "length",
    group: "Computation",
    factor: 2.647e-8,
    resultPhrase: "of single-spaced paper stack",
    basis: "Derived from the brainstormed parliamentary-answer note: 20.4 GB as 5.4 million pages, at 0.1 mm per sheet.",
    sources: [
      { label: "TheyWorkForYou written answer", url: "http://www.theyworkforyou.com/wrans/?id=2005-11-21b.28485.h" },
    ],
    goodRange: [0.001, 10000000],
    glyph: "data",
    accent: "#426f83",
  },
  {
    id: "floppy-disks",
    name: "Floppy disks",
    shortName: "floppies",
    input: "data",
    output: "count",
    group: "Computation",
    factor: 1 / 1440000,
    unitSingular: "floppy disk",
    unitPlural: "floppy disks",
    resultPhrase: "at 1.44 MB each",
    basis: "Uses 1.44 MB for the familiar 3.5 inch high-density floppy.",
    sources: [
      { label: "Wikipedia: Floppy disk", url: "https://en.wikipedia.org/wiki/Floppy_disk" },
    ],
    goodRange: [0.1, 10000000000],
    glyph: "data",
    accent: "#4b5e9a",
  },
  {
    id: "dvds",
    name: "DVDs",
    shortName: "DVDs",
    input: "data",
    output: "count",
    group: "Computation",
    factor: 1 / 4700000000,
    unitSingular: "single-layer DVD",
    unitPlural: "single-layer DVDs",
    resultPhrase: "of data",
    basis: "Uses 4.7 GB for a single-layer DVD.",
    sources: [
      { label: "Wikipedia: DVD", url: "https://en.wikipedia.org/wiki/DVD" },
    ],
    goodRange: [0.01, 1000000000],
    glyph: "data",
    accent: "#6d5aa6",
  },
  {
    id: "hummingbird-frequency",
    name: "Hummingbird wingbeats",
    shortName: "hummingbirds",
    input: "frequency",
    output: "multiple",
    group: "Nature",
    factor: 1 / 50,
    unitSingular: "hummingbird wingbeat rate",
    unitPlural: "hummingbird wingbeat rates",
    resultPhrase: "at 50 Hz",
    basis: "Uses 50 beats per second as a round hummingbird wingbeat reference.",
    sources: [
      { label: "Wikipedia: Hummingbird", url: "https://en.wikipedia.org/wiki/Hummingbird" },
    ],
    goodRange: [0.01, 1000000],
    glyph: "spark",
    accent: "#2f8b83",
  },
  {
    id: "mains-frequency",
    name: "Mains electricity",
    shortName: "50 Hz mains",
    input: "frequency",
    output: "multiple",
    group: "Everyday",
    factor: 1 / 50,
    unitSingular: "European mains frequency",
    unitPlural: "European mains frequencies",
    resultPhrase: "at 50 Hz",
    basis: "Uses 50 Hz, the common AC mains frequency in Europe.",
    sources: [
      { label: "Wikipedia: Utility frequency", url: "https://en.wikipedia.org/wiki/Utility_frequency" },
    ],
    goodRange: [0.01, 1000000],
    glyph: "spark",
    accent: "#d29b2d",
  },
  {
    id: "concert-a",
    name: "Concert A notes",
    shortName: "A440 notes",
    input: "frequency",
    output: "multiple",
    group: "Culture",
    factor: 1 / 440,
    unitSingular: "concert A",
    unitPlural: "concert A notes",
    resultPhrase: "at 440 Hz",
    basis: "Uses A440, the common tuning reference.",
    sources: [
      { label: "Wikipedia: A440", url: "https://en.wikipedia.org/wiki/A440_(pitch_standard)" },
    ],
    goodRange: [0.01, 1000000],
    glyph: "spark",
    accent: "#9b5678",
  },
];
